### ISSUE TITLE
How to use this repo can you please add documentation

### ISSUE THREAD

**Issue by keshrisohit** [alexhaislip/BitClout#13]

**Comment by alexhaislip** [comment]
@keshrisohit @nickmatthews713  and I will be adding detailed documentation after some low-hanging fruit is picked. You can find the first thing we are actively working on here (feel free to give any suggestions) --> `https://github.com/alexhaislip/BitClout/issues/2`

**Comment by alexhaislip** [comment]
@nickmatthews713 let's consider using Docker for ease of use? Thoughts?
